services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /Users/piyushkhurana/Projects/Frontend_Project/videoStreamingWebApp/video_streaming_web_app
    ports:
      - 3000:3000
    command: ["nodemon", "server.js"]
    environment:
      - NODE_ENV=development