version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: ["nodemon", "server.js"]
    environment:
      - NODE_ENV=development
